//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:03:05 AM CEST 
//


package rs.xml.ws.filterandsearch.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarXML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarXML"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="plateNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="model" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML"/&gt;
 *         &lt;element name="brand" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML"/&gt;
 *         &lt;element name="fuelType" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML"/&gt;
 *         &lt;element name="transmission" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML"/&gt;
 *         &lt;element name="carClass" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML"/&gt;
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="priceList" type="{www.rent-a-car.ws.xml.rs/filter-and-search}PriceListXML"/&gt;
 *         &lt;element name="mileage" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="distanceAllowed" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="protection" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="childSeats" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="images"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="image" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarXML", propOrder = {
    "id",
    "plateNumber",
    "model",
    "brand",
    "fuelType",
    "transmission",
    "carClass",
    "company",
    "owner",
    "priceList",
    "mileage",
    "distanceAllowed",
    "protection",
    "childSeats",
    "discount",
    "images"
})
public class CarXML {

    protected long id;
    @XmlElement(required = true)
    protected String plateNumber;
    @XmlElement(required = true)
    protected IdNameXML model;
    @XmlElement(required = true)
    protected IdNameXML brand;
    @XmlElement(required = true)
    protected IdNameXML fuelType;
    @XmlElement(required = true)
    protected IdNameXML transmission;
    @XmlElement(required = true)
    protected IdNameXML carClass;
    protected long company;
    protected long owner;
    @XmlElement(required = true)
    protected PriceListXML priceList;
    protected double mileage;
    protected double distanceAllowed;
    protected boolean protection;
    protected int childSeats;
    protected double discount;
    @XmlElement(required = true)
    protected CarXML.Images images;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the plateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * Sets the value of the plateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateNumber(String value) {
        this.plateNumber = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link IdNameXML }
     *     
     */
    public IdNameXML getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdNameXML }
     *     
     */
    public void setModel(IdNameXML value) {
        this.model = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link IdNameXML }
     *     
     */
    public IdNameXML getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdNameXML }
     *     
     */
    public void setBrand(IdNameXML value) {
        this.brand = value;
    }

    /**
     * Gets the value of the fuelType property.
     * 
     * @return
     *     possible object is
     *     {@link IdNameXML }
     *     
     */
    public IdNameXML getFuelType() {
        return fuelType;
    }

    /**
     * Sets the value of the fuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdNameXML }
     *     
     */
    public void setFuelType(IdNameXML value) {
        this.fuelType = value;
    }

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link IdNameXML }
     *     
     */
    public IdNameXML getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdNameXML }
     *     
     */
    public void setTransmission(IdNameXML value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the carClass property.
     * 
     * @return
     *     possible object is
     *     {@link IdNameXML }
     *     
     */
    public IdNameXML getCarClass() {
        return carClass;
    }

    /**
     * Sets the value of the carClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdNameXML }
     *     
     */
    public void setCarClass(IdNameXML value) {
        this.carClass = value;
    }

    /**
     * Gets the value of the company property.
     * 
     */
    public long getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     */
    public void setCompany(long value) {
        this.company = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     */
    public long getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     */
    public void setOwner(long value) {
        this.owner = value;
    }

    /**
     * Gets the value of the priceList property.
     * 
     * @return
     *     possible object is
     *     {@link PriceListXML }
     *     
     */
    public PriceListXML getPriceList() {
        return priceList;
    }

    /**
     * Sets the value of the priceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceListXML }
     *     
     */
    public void setPriceList(PriceListXML value) {
        this.priceList = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     */
    public double getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     */
    public void setMileage(double value) {
        this.mileage = value;
    }

    /**
     * Gets the value of the distanceAllowed property.
     * 
     */
    public double getDistanceAllowed() {
        return distanceAllowed;
    }

    /**
     * Sets the value of the distanceAllowed property.
     * 
     */
    public void setDistanceAllowed(double value) {
        this.distanceAllowed = value;
    }

    /**
     * Gets the value of the protection property.
     * 
     */
    public boolean isProtection() {
        return protection;
    }

    /**
     * Sets the value of the protection property.
     * 
     */
    public void setProtection(boolean value) {
        this.protection = value;
    }

    /**
     * Gets the value of the childSeats property.
     * 
     */
    public int getChildSeats() {
        return childSeats;
    }

    /**
     * Sets the value of the childSeats property.
     * 
     */
    public void setChildSeats(int value) {
        this.childSeats = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     */
    public double getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(double value) {
        this.discount = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link CarXML.Images }
     *     
     */
    public CarXML.Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarXML.Images }
     *     
     */
    public void setImages(CarXML.Images value) {
        this.images = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="image" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "image"
    })
    public static class Images {

        @XmlElement(required = true)
        protected List<IdNameXML> image;

        /**
         * Gets the value of the image property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the image property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IdNameXML }
         * 
         * 
         */
        public List<IdNameXML> getImage() {
            if (image == null) {
                image = new ArrayList<IdNameXML>();
            }
            return this.image;
        }

    }

}
