//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:03:05 AM CEST 
//


package rs.xml.ws.filterandsearch.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.xml.ws.filterandsearch.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.xml.ws.filterandsearch.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarXML }
     * 
     */
    public CarXML createCarXML() {
        return new CarXML();
    }

    /**
     * Create an instance of {@link GetAllPriceListsRequest }
     * 
     */
    public GetAllPriceListsRequest createGetAllPriceListsRequest() {
        return new GetAllPriceListsRequest();
    }

    /**
     * Create an instance of {@link GetAllPriceListsResponse }
     * 
     */
    public GetAllPriceListsResponse createGetAllPriceListsResponse() {
        return new GetAllPriceListsResponse();
    }

    /**
     * Create an instance of {@link PriceListXML }
     * 
     */
    public PriceListXML createPriceListXML() {
        return new PriceListXML();
    }

    /**
     * Create an instance of {@link CreatePriceListRequest }
     * 
     */
    public CreatePriceListRequest createCreatePriceListRequest() {
        return new CreatePriceListRequest();
    }

    /**
     * Create an instance of {@link CreateCarRequest }
     * 
     */
    public CreateCarRequest createCreateCarRequest() {
        return new CreateCarRequest();
    }

    /**
     * Create an instance of {@link ApiResponseXML }
     * 
     */
    public ApiResponseXML createApiResponseXML() {
        return new ApiResponseXML();
    }

    /**
     * Create an instance of {@link RemoveCarRequest }
     * 
     */
    public RemoveCarRequest createRemoveCarRequest() {
        return new RemoveCarRequest();
    }

    /**
     * Create an instance of {@link UpdateCarRequest }
     * 
     */
    public UpdateCarRequest createUpdateCarRequest() {
        return new UpdateCarRequest();
    }

    /**
     * Create an instance of {@link GetAllCompanyDataRequest }
     * 
     */
    public GetAllCompanyDataRequest createGetAllCompanyDataRequest() {
        return new GetAllCompanyDataRequest();
    }

    /**
     * Create an instance of {@link GetAllCompanyDataResponse }
     * 
     */
    public GetAllCompanyDataResponse createGetAllCompanyDataResponse() {
        return new GetAllCompanyDataResponse();
    }

    /**
     * Create an instance of {@link IdNameXML }
     * 
     */
    public IdNameXML createIdNameXML() {
        return new IdNameXML();
    }

    /**
     * Create an instance of {@link CarXML.Images }
     * 
     */
    public CarXML.Images createCarXMLImages() {
        return new CarXML.Images();
    }

}
