//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:03:05 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.rent-a-car.ws.xml.rs/filter-and-search", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.xml.ws.filterandsearch.soap;
