//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:26:55 AM CEST 
//


package rs.xml.ws.ratingandcomment.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.xml.ws.ratingandcomment.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.xml.ws.ratingandcomment.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommentRequest }
     * 
     */
    public CommentRequest createCommentRequest() {
        return new CommentRequest();
    }

    /**
     * Create an instance of {@link CommentXML }
     * 
     */
    public CommentXML createCommentXML() {
        return new CommentXML();
    }

    /**
     * Create an instance of {@link CommentResponse }
     * 
     */
    public CommentResponse createCommentResponse() {
        return new CommentResponse();
    }

    /**
     * Create an instance of {@link AllCommentsRequest }
     * 
     */
    public AllCommentsRequest createAllCommentsRequest() {
        return new AllCommentsRequest();
    }

    /**
     * Create an instance of {@link AllCommentsResponse }
     * 
     */
    public AllCommentsResponse createAllCommentsResponse() {
        return new AllCommentsResponse();
    }

    /**
     * Create an instance of {@link AllRatingRequest }
     * 
     */
    public AllRatingRequest createAllRatingRequest() {
        return new AllRatingRequest();
    }

    /**
     * Create an instance of {@link AllRatingResponse }
     * 
     */
    public AllRatingResponse createAllRatingResponse() {
        return new AllRatingResponse();
    }

    /**
     * Create an instance of {@link RatingXML }
     * 
     */
    public RatingXML createRatingXML() {
        return new RatingXML();
    }

}
