//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.05 at 01:23:37 AM CEST 
//


package rs.xml.ws.agentsoapconsumer.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cars" type="{www.rent-a-car.ws.xml.rs/filter-and-search}CarXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="brands" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="models" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fuelTypes" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="carClasses" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="transmissions" type="{www.rent-a-car.ws.xml.rs/filter-and-search}IdNameXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="priceLists" type="{www.rent-a-car.ws.xml.rs/filter-and-search}PriceListXML" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cars",
    "brands",
    "models",
    "fuelTypes",
    "carClasses",
    "transmissions",
    "priceLists"
})
@XmlRootElement(name = "getAllCompanyDataResponse")
public class GetAllCompanyDataResponse {

    protected List<CarXML> cars;
    protected List<IdNameXML> brands;
    protected List<IdNameXML> models;
    protected List<IdNameXML> fuelTypes;
    protected List<IdNameXML> carClasses;
    protected List<IdNameXML> transmissions;
    protected List<PriceListXML> priceLists;

    /**
     * Gets the value of the cars property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cars property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCars().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CarXML }
     * 
     * 
     */
    public List<CarXML> getCars() {
        if (cars == null) {
            cars = new ArrayList<CarXML>();
        }
        return this.cars;
    }

    /**
     * Gets the value of the brands property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brands property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrands().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdNameXML }
     * 
     * 
     */
    public List<IdNameXML> getBrands() {
        if (brands == null) {
            brands = new ArrayList<IdNameXML>();
        }
        return this.brands;
    }

    /**
     * Gets the value of the models property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the models property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdNameXML }
     * 
     * 
     */
    public List<IdNameXML> getModels() {
        if (models == null) {
            models = new ArrayList<IdNameXML>();
        }
        return this.models;
    }

    /**
     * Gets the value of the fuelTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fuelTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFuelTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdNameXML }
     * 
     * 
     */
    public List<IdNameXML> getFuelTypes() {
        if (fuelTypes == null) {
            fuelTypes = new ArrayList<IdNameXML>();
        }
        return this.fuelTypes;
    }

    /**
     * Gets the value of the carClasses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carClasses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarClasses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdNameXML }
     * 
     * 
     */
    public List<IdNameXML> getCarClasses() {
        if (carClasses == null) {
            carClasses = new ArrayList<IdNameXML>();
        }
        return this.carClasses;
    }

    /**
     * Gets the value of the transmissions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transmissions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransmissions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdNameXML }
     * 
     * 
     */
    public List<IdNameXML> getTransmissions() {
        if (transmissions == null) {
            transmissions = new ArrayList<IdNameXML>();
        }
        return this.transmissions;
    }

    /**
     * Gets the value of the priceLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceListXML }
     * 
     * 
     */
    public List<PriceListXML> getPriceLists() {
        if (priceLists == null) {
            priceLists = new ArrayList<PriceListXML>();
        }
        return this.priceLists;
    }

}
