//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.05 at 01:23:37 AM CEST 
//


package rs.xml.ws.agentsoapconsumer.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.xml.ws.agentsoapconsumer.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.xml.ws.agentsoapconsumer.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarXML }
     * 
     */
    public CarXML createCarXML() {
        return new CarXML();
    }

    /**
     * Create an instance of {@link GetAllPriceListsRequest }
     * 
     */
    public GetAllPriceListsRequest createGetAllPriceListsRequest() {
        return new GetAllPriceListsRequest();
    }

    /**
     * Create an instance of {@link GetAllPriceListsResponse }
     * 
     */
    public GetAllPriceListsResponse createGetAllPriceListsResponse() {
        return new GetAllPriceListsResponse();
    }

    /**
     * Create an instance of {@link PriceListXML }
     * 
     */
    public PriceListXML createPriceListXML() {
        return new PriceListXML();
    }

    /**
     * Create an instance of {@link CreatePriceListRequest }
     * 
     */
    public CreatePriceListRequest createCreatePriceListRequest() {
        return new CreatePriceListRequest();
    }

    /**
     * Create an instance of {@link CreateCarRequest }
     * 
     */
    public CreateCarRequest createCreateCarRequest() {
        return new CreateCarRequest();
    }

    /**
     * Create an instance of {@link ApiResponseXML }
     * 
     */
    public ApiResponseXML createApiResponseXML() {
        return new ApiResponseXML();
    }

    /**
     * Create an instance of {@link RemoveCarRequest }
     * 
     */
    public RemoveCarRequest createRemoveCarRequest() {
        return new RemoveCarRequest();
    }

    /**
     * Create an instance of {@link UpdateCarRequest }
     * 
     */
    public UpdateCarRequest createUpdateCarRequest() {
        return new UpdateCarRequest();
    }

    /**
     * Create an instance of {@link GetAllCompanyDataRequest }
     * 
     */
    public GetAllCompanyDataRequest createGetAllCompanyDataRequest() {
        return new GetAllCompanyDataRequest();
    }

    /**
     * Create an instance of {@link GetAllCompanyDataResponse }
     * 
     */
    public GetAllCompanyDataResponse createGetAllCompanyDataResponse() {
        return new GetAllCompanyDataResponse();
    }

    /**
     * Create an instance of {@link IdNameXML }
     * 
     */
    public IdNameXML createIdNameXML() {
        return new IdNameXML();
    }

    /**
     * Create an instance of {@link CommentRequest }
     * 
     */
    public CommentRequest createCommentRequest() {
        return new CommentRequest();
    }

    /**
     * Create an instance of {@link CommentXML }
     * 
     */
    public CommentXML createCommentXML() {
        return new CommentXML();
    }

    /**
     * Create an instance of {@link CommentResponse }
     * 
     */
    public CommentResponse createCommentResponse() {
        return new CommentResponse();
    }

    /**
     * Create an instance of {@link AllCommentsRequest }
     * 
     */
    public AllCommentsRequest createAllCommentsRequest() {
        return new AllCommentsRequest();
    }

    /**
     * Create an instance of {@link AllCommentsResponse }
     * 
     */
    public AllCommentsResponse createAllCommentsResponse() {
        return new AllCommentsResponse();
    }

    /**
     * Create an instance of {@link AllRatingRequest }
     * 
     */
    public AllRatingRequest createAllRatingRequest() {
        return new AllRatingRequest();
    }

    /**
     * Create an instance of {@link AllRatingResponse }
     * 
     */
    public AllRatingResponse createAllRatingResponse() {
        return new AllRatingResponse();
    }

    /**
     * Create an instance of {@link RatingXML }
     * 
     */
    public RatingXML createRatingXML() {
        return new RatingXML();
    }

    /**
     * Create an instance of {@link AllMessagesRequest }
     * 
     */
    public AllMessagesRequest createAllMessagesRequest() {
        return new AllMessagesRequest();
    }

    /**
     * Create an instance of {@link MessagesResponse }
     * 
     */
    public MessagesResponse createMessagesResponse() {
        return new MessagesResponse();
    }

    /**
     * Create an instance of {@link MessageXML }
     * 
     */
    public MessageXML createMessageXML() {
        return new MessageXML();
    }

    /**
     * Create an instance of {@link CreateMessageRequest }
     * 
     */
    public CreateMessageRequest createCreateMessageRequest() {
        return new CreateMessageRequest();
    }

    /**
     * Create an instance of {@link CreateMessageResponse }
     * 
     */
    public CreateMessageResponse createCreateMessageResponse() {
        return new CreateMessageResponse();
    }

    /**
     * Create an instance of {@link AllAppointmentsRequest }
     * 
     */
    public AllAppointmentsRequest createAllAppointmentsRequest() {
        return new AllAppointmentsRequest();
    }

    /**
     * Create an instance of {@link AllAppointmentsResponse }
     * 
     */
    public AllAppointmentsResponse createAllAppointmentsResponse() {
        return new AllAppointmentsResponse();
    }

    /**
     * Create an instance of {@link AppointmentXML }
     * 
     */
    public AppointmentXML createAppointmentXML() {
        return new AppointmentXML();
    }

    /**
     * Create an instance of {@link CreateAppointmentRequest }
     * 
     */
    public CreateAppointmentRequest createCreateAppointmentRequest() {
        return new CreateAppointmentRequest();
    }

    /**
     * Create an instance of {@link CreateAppointmentResponse }
     * 
     */
    public CreateAppointmentResponse createCreateAppointmentResponse() {
        return new CreateAppointmentResponse();
    }

    /**
     * Create an instance of {@link AppointmentItemXML }
     * 
     */
    public AppointmentItemXML createAppointmentItemXML() {
        return new AppointmentItemXML();
    }

    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link UserXML }
     * 
     */
    public UserXML createUserXML() {
        return new UserXML();
    }

    /**
     * Create an instance of {@link RoleXML }
     * 
     */
    public RoleXML createRoleXML() {
        return new RoleXML();
    }

    /**
     * Create an instance of {@link CarXML.Images }
     * 
     */
    public CarXML.Images createCarXMLImages() {
        return new CarXML.Images();
    }

}
